/* Office Resources content. Generated by the Edit panel.
   Replace your site's data.js with this file to publish changes. */

/* Passcode for the Edit panel (some light deterrent, not strong security). */
const CONFIG = {
  "editPasscode": "office"
};

const SITE = {
  "title": "Office Resources",
  "subtitle": "Forms and quick links",
  "sections": [
    {
      "title": "Forms",
      "items": [
        {
          "type": "pdf",
          "title": "CBC Form",
          "description": "Criminal Background Check (CBC).",
          "url": "files/CBC-CS-K12-Outreach-Fall-2026.pdf",
          "size": "normal"
        },
        {
          "type": "pdf",
          "title": "Image Release Form",
          "description": "Consent form for use of photos and images.",
          "url": "files/Media-Release-Form.pdf",
          "size": "normal"
        }
      ]
    },
    {
      "title": "Mentor Forms",
      "items": [
        {
          "type": "pdf",
          "title": "Mentor Contract",
          "description": "Agree to all these. (will change later)",
          "url": "files/FS26-Mentor-Contract.pdf",
          "size": "normal"
        }
      ]
    }
  ]
};
